### ISSUE TITLE
[1.18.2] Crash on Launch

### ISSUE THREAD

**Issue by Tellik** [Jackiecrazy/EnchantLimiter#1]
Hoping you would be able to do something with this and get this mod working.

```
[04:21:59] [main/WARN]: Reference map 'enchantlimiter.refmap.json' for enchantlimiter.mixins.json could not be read. If this is a development environment you can ignore this message
[04:22:00] [pool-3-thread-1/FATAL]: Mixin apply failed enchantlimiter.mixins.json:ItemStackMixin -> net.minecraft.world.item.ItemStack: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method enchant in enchantlimiter.mixins.json:ItemStackMixin was not located in the target class net.minecraft.world.item.ItemStack. No refMap loaded.
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method enchant in enchantlimiter.mixins.json:ItemStackMixin was not located in the target class net.minecraft.world.item.ItemStack. No refMap loaded.
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:442) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:415) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:343) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.1.3.jar:9.1.3+9.1.3+main.9b69c82a]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.core.cauldron.CauldronInteraction.m_175645_(CauldronInteraction.java:39) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.Util.m_137469_(Util.java:351) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.core.cauldron.CauldronInteraction.m_175617_(CauldronInteraction.java:39) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.core.cauldron.CauldronInteraction.<clinit>(CauldronInteraction.java:33) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.level.block.CauldronBlock.<init>(CauldronBlock.java:17) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:354) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.level.levelgen.carver.CarverDebugSettings.<clinit>(CarverDebugSettings.java:9) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.level.levelgen.carver.CarverConfiguration.m_190634_(CarverConfiguration.java:16) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar%2334!/:?]
	at net.minecraft.world.level.levelgen.carver.CarverConfiguration.<clinit>(CarverConfiguration.java:12) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.level.levelgen.carver.WorldCarver.<clinit>(WorldCarver.java:30) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.data.worldgen.Carvers.<clinit>(Carvers.java:19) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.data.BuiltinRegistries.m_206400_(BuiltinRegistries.java:45) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.data.BuiltinRegistries.m_206392_(BuiltinRegistries.java:101) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:?]
	at net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:100) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:633) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:44) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:138) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by Jackiecrazy** [comment]
This should be fixed by latest release. I didn't configure the compilation properly...

**Comment by Tellik** [comment]
Perfect, everything is looking good.

Also, thank you for this. It's just what I've been looking for.
